---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/pgo --help
    register: pgo_test_output
  - name: pgo --help
    debug:
      msg: '{{ pgo_test_output.stdout }}'
