---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ pgo_url }} to {{ pgo_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ pgo_url }}'
    dest: '{{ pgo_exe }}'
    mode: 0755
    checksum: '{{ pgo_checksum }}'
- name: linking {{ pgo_link }} to {{ pgo_exe }}
  become: true
  become_user: root
  file:
    src: '{{ pgo_exe }}'
    dest: '{{ pgo_link }}'
    state: link
